/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;
import java.util.ArrayList;
public class App {

    public static int toplam(ArrayList<Integer> array, int baslangic, int son) {
        System.out.println("Sum positive numbers in a given index range");
        if (array == null) return -1;

        if(baslangic > array.size() - 1 || son > array.size() || baslangic > son){
            return -1;
        }

        if(son == baslangic){
            return -1;
        }

        int toplam = 0;
    
        for (int i = baslangic; i < son; i++) {
           toplam += array.get(i);
        }
        return toplam;
    }




    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
